version: "3"
services:
  arangodb:
    image: arangodb:3.11.8
    ports:
      - 8529:8529
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - persistence:/var/lib/arangodb3

volumes:
  persistence:
