// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: admin/v1/events.proto

package adminv1

import (
	utils "github.com/amaury95/protoc-gen-graphify/utils"
	graphql "github.com/graphql-go/graphql"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminCreatedPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Element []byte `protobuf:"bytes,2,opt,name=element,proto3" json:"element,omitempty"`
	Admin   *Admin `protobuf:"bytes,3,opt,name=admin,proto3" json:"admin,omitempty"`
}

func (x *AdminCreatedPayload) Reset() {
	*x = AdminCreatedPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_v1_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminCreatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminCreatedPayload) ProtoMessage() {}

func (x *AdminCreatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminCreatedPayload.ProtoReflect.Descriptor instead.
func (*AdminCreatedPayload) Descriptor() ([]byte, []int) {
	return file_admin_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *AdminCreatedPayload) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AdminCreatedPayload) GetElement() []byte {
	if x != nil {
		return x.Element
	}
	return nil
}

func (x *AdminCreatedPayload) GetAdmin() *Admin {
	if x != nil {
		return x.Admin
	}
	return nil
}

type AdminUpdatedPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Element []byte `protobuf:"bytes,1,opt,name=element,proto3" json:"element,omitempty"`
	Admin   *Admin `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
}

func (x *AdminUpdatedPayload) Reset() {
	*x = AdminUpdatedPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_v1_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminUpdatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdatedPayload) ProtoMessage() {}

func (x *AdminUpdatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdatedPayload.ProtoReflect.Descriptor instead.
func (*AdminUpdatedPayload) Descriptor() ([]byte, []int) {
	return file_admin_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *AdminUpdatedPayload) GetElement() []byte {
	if x != nil {
		return x.Element
	}
	return nil
}

func (x *AdminUpdatedPayload) GetAdmin() *Admin {
	if x != nil {
		return x.Admin
	}
	return nil
}

type AdminReplacedPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Element []byte `protobuf:"bytes,1,opt,name=element,proto3" json:"element,omitempty"`
	Admin   *Admin `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
}

func (x *AdminReplacedPayload) Reset() {
	*x = AdminReplacedPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_v1_events_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminReplacedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminReplacedPayload) ProtoMessage() {}

func (x *AdminReplacedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_events_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminReplacedPayload.ProtoReflect.Descriptor instead.
func (*AdminReplacedPayload) Descriptor() ([]byte, []int) {
	return file_admin_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *AdminReplacedPayload) GetElement() []byte {
	if x != nil {
		return x.Element
	}
	return nil
}

func (x *AdminReplacedPayload) GetAdmin() *Admin {
	if x != nil {
		return x.Admin
	}
	return nil
}

type AdminDeletedPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Admin *Admin `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
}

func (x *AdminDeletedPayload) Reset() {
	*x = AdminDeletedPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_v1_events_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminDeletedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeletedPayload) ProtoMessage() {}

func (x *AdminDeletedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_events_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeletedPayload.ProtoReflect.Descriptor instead.
func (*AdminDeletedPayload) Descriptor() ([]byte, []int) {
	return file_admin_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *AdminDeletedPayload) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AdminDeletedPayload) GetAdmin() *Admin {
	if x != nil {
		return x.Admin
	}
	return nil
}

var File_admin_v1_events_proto protoreflect.FileDescriptor

var file_admin_v1_events_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76,
	0x31, 0x1a, 0x14, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68, 0x0a, 0x13, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x05, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x05, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x22, 0x56, 0x0a, 0x13, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x25, 0x0a, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x52, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x22, 0x57, 0x0a, 0x14, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x05, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x05, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x22, 0x4e, 0x0a, 0x13, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x05, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x05, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x42, 0x9d, 0x01, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x2e, 0x76, 0x31, 0x42, 0x0b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x6d, 0x61, 0x75, 0x72, 0x79, 0x39, 0x35, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x69, 0x66, 0x79,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x41, 0x58, 0x58, 0xaa, 0x02, 0x08, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x08, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x5c, 0x56, 0x31, 0xe2,
	0x02, 0x14, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x09, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x3a, 0x3a,
	0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_admin_v1_events_proto_rawDescOnce sync.Once
	file_admin_v1_events_proto_rawDescData = file_admin_v1_events_proto_rawDesc
)

func file_admin_v1_events_proto_rawDescGZIP() []byte {
	file_admin_v1_events_proto_rawDescOnce.Do(func() {
		file_admin_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_admin_v1_events_proto_rawDescData)
	})
	return file_admin_v1_events_proto_rawDescData
}

var file_admin_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_admin_v1_events_proto_goTypes = []interface{}{
	(*AdminCreatedPayload)(nil),  // 0: admin.v1.AdminCreatedPayload
	(*AdminUpdatedPayload)(nil),  // 1: admin.v1.AdminUpdatedPayload
	(*AdminReplacedPayload)(nil), // 2: admin.v1.AdminReplacedPayload
	(*AdminDeletedPayload)(nil),  // 3: admin.v1.AdminDeletedPayload
	(*Admin)(nil),                // 4: admin.v1.Admin
}
var file_admin_v1_events_proto_depIdxs = []int32{
	4, // 0: admin.v1.AdminCreatedPayload.admin:type_name -> admin.v1.Admin
	4, // 1: admin.v1.AdminUpdatedPayload.admin:type_name -> admin.v1.Admin
	4, // 2: admin.v1.AdminReplacedPayload.admin:type_name -> admin.v1.Admin
	4, // 3: admin.v1.AdminDeletedPayload.admin:type_name -> admin.v1.Admin
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_admin_v1_events_proto_init() }
func file_admin_v1_events_proto_init() {
	if File_admin_v1_events_proto != nil {
		return
	}
	file_admin_v1_admin_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_admin_v1_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminCreatedPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_v1_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminUpdatedPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_v1_events_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminReplacedPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_v1_events_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminDeletedPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_admin_v1_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_admin_v1_events_proto_goTypes,
		DependencyIndexes: file_admin_v1_events_proto_depIdxs,
		MessageInfos:      file_admin_v1_events_proto_msgTypes,
	}.Build()
	File_admin_v1_events_proto = out.File
	file_admin_v1_events_proto_rawDesc = nil
	file_admin_v1_events_proto_goTypes = nil
	file_admin_v1_events_proto_depIdxs = nil
}

/*
	Graphql object
*/

/* Argument ... */
func (*AdminCreatedPayload) Argument() graphql.FieldConfigArgument {
	return graphql.FieldConfigArgument{
		"key": &graphql.ArgumentConfig{
			Type: graphql.String,
		},
		"element": &graphql.ArgumentConfig{
			Type: graphql.String,
		},
		"admin": &graphql.ArgumentConfig{
			Type: Admin_Input,
		},
	}
}

/* Output ... */
func (*AdminCreatedPayload) Output() graphql.Output {
	return AdminCreatedPayload_Object
}

/* Object ... */
func (*AdminCreatedPayload) Object() *graphql.Object {
	return AdminCreatedPayload_Object
}

var AdminCreatedPayload_Object = graphql.NewObject(graphql.ObjectConfig{
	Name: "AdminCreatedPayload",
	Fields: graphql.Fields{
		"key": &graphql.Field{
			Type: graphql.String,
		},
		"element": &graphql.Field{
			Type: utils.Bytes,
		},
		"admin": &graphql.Field{
			Type: Admin_Object,
		},
	},
	Description: "",
})

var AdminCreatedPayload_Input = graphql.NewInputObject(graphql.InputObjectConfig{
	Name: "AdminCreatedPayload_Input",
	Fields: graphql.InputObjectConfigFieldMap{
		"key": &graphql.InputObjectFieldConfig{
			Type: graphql.String,
		},
		"element": &graphql.InputObjectFieldConfig{
			Type: graphql.String,
		},
		"admin": &graphql.InputObjectFieldConfig{
			Type: Admin_Input,
		},
	},
})

/* Argument ... */
func (*AdminUpdatedPayload) Argument() graphql.FieldConfigArgument {
	return graphql.FieldConfigArgument{
		"element": &graphql.ArgumentConfig{
			Type: graphql.String,
		},
		"admin": &graphql.ArgumentConfig{
			Type: Admin_Input,
		},
	}
}

/* Output ... */
func (*AdminUpdatedPayload) Output() graphql.Output {
	return AdminUpdatedPayload_Object
}

/* Object ... */
func (*AdminUpdatedPayload) Object() *graphql.Object {
	return AdminUpdatedPayload_Object
}

var AdminUpdatedPayload_Object = graphql.NewObject(graphql.ObjectConfig{
	Name: "AdminUpdatedPayload",
	Fields: graphql.Fields{
		"element": &graphql.Field{
			Type: utils.Bytes,
		},
		"admin": &graphql.Field{
			Type: Admin_Object,
		},
	},
	Description: "",
})

var AdminUpdatedPayload_Input = graphql.NewInputObject(graphql.InputObjectConfig{
	Name: "AdminUpdatedPayload_Input",
	Fields: graphql.InputObjectConfigFieldMap{
		"element": &graphql.InputObjectFieldConfig{
			Type: graphql.String,
		},
		"admin": &graphql.InputObjectFieldConfig{
			Type: Admin_Input,
		},
	},
})

/* Argument ... */
func (*AdminReplacedPayload) Argument() graphql.FieldConfigArgument {
	return graphql.FieldConfigArgument{
		"element": &graphql.ArgumentConfig{
			Type: graphql.String,
		},
		"admin": &graphql.ArgumentConfig{
			Type: Admin_Input,
		},
	}
}

/* Output ... */
func (*AdminReplacedPayload) Output() graphql.Output {
	return AdminReplacedPayload_Object
}

/* Object ... */
func (*AdminReplacedPayload) Object() *graphql.Object {
	return AdminReplacedPayload_Object
}

var AdminReplacedPayload_Object = graphql.NewObject(graphql.ObjectConfig{
	Name: "AdminReplacedPayload",
	Fields: graphql.Fields{
		"element": &graphql.Field{
			Type: utils.Bytes,
		},
		"admin": &graphql.Field{
			Type: Admin_Object,
		},
	},
	Description: "",
})

var AdminReplacedPayload_Input = graphql.NewInputObject(graphql.InputObjectConfig{
	Name: "AdminReplacedPayload_Input",
	Fields: graphql.InputObjectConfigFieldMap{
		"element": &graphql.InputObjectFieldConfig{
			Type: graphql.String,
		},
		"admin": &graphql.InputObjectFieldConfig{
			Type: Admin_Input,
		},
	},
})

/* Argument ... */
func (*AdminDeletedPayload) Argument() graphql.FieldConfigArgument {
	return graphql.FieldConfigArgument{
		"key": &graphql.ArgumentConfig{
			Type: graphql.String,
		},
		"admin": &graphql.ArgumentConfig{
			Type: Admin_Input,
		},
	}
}

/* Output ... */
func (*AdminDeletedPayload) Output() graphql.Output {
	return AdminDeletedPayload_Object
}

/* Object ... */
func (*AdminDeletedPayload) Object() *graphql.Object {
	return AdminDeletedPayload_Object
}

var AdminDeletedPayload_Object = graphql.NewObject(graphql.ObjectConfig{
	Name: "AdminDeletedPayload",
	Fields: graphql.Fields{
		"key": &graphql.Field{
			Type: graphql.String,
		},
		"admin": &graphql.Field{
			Type: Admin_Object,
		},
	},
	Description: "",
})

var AdminDeletedPayload_Input = graphql.NewInputObject(graphql.InputObjectConfig{
	Name: "AdminDeletedPayload_Input",
	Fields: graphql.InputObjectConfigFieldMap{
		"key": &graphql.InputObjectFieldConfig{
			Type: graphql.String,
		},
		"admin": &graphql.InputObjectFieldConfig{
			Type: Admin_Input,
		},
	},
})

/*
	Graphify schema module
*/

/* Schema ... */
func (*AdminCreatedPayload) Schema() map[string]interface{} {
	return map[string]interface{}{
		"name": "AdminCreatedPayload",
		"fields": []interface{}{
			map[string]interface{}{
				"name": "key",
				"type": "string",
			},
			map[string]interface{}{
				"name": "element",
				"type": "bytes",
			},
			map[string]interface{}{
				"name":     "admin",
				"optional": true,
				"type":     "message",
				"schema":   new(Admin).Schema(),
			},
		},
		"oneofs": map[string]interface{}{},
	}
}

/* Schema ... */
func (*AdminUpdatedPayload) Schema() map[string]interface{} {
	return map[string]interface{}{
		"name": "AdminUpdatedPayload",
		"fields": []interface{}{
			map[string]interface{}{
				"name": "element",
				"type": "bytes",
			},
			map[string]interface{}{
				"name":     "admin",
				"optional": true,
				"type":     "message",
				"schema":   new(Admin).Schema(),
			},
		},
		"oneofs": map[string]interface{}{},
	}
}

/* Schema ... */
func (*AdminReplacedPayload) Schema() map[string]interface{} {
	return map[string]interface{}{
		"name": "AdminReplacedPayload",
		"fields": []interface{}{
			map[string]interface{}{
				"name": "element",
				"type": "bytes",
			},
			map[string]interface{}{
				"name":     "admin",
				"optional": true,
				"type":     "message",
				"schema":   new(Admin).Schema(),
			},
		},
		"oneofs": map[string]interface{}{},
	}
}

/* Schema ... */
func (*AdminDeletedPayload) Schema() map[string]interface{} {
	return map[string]interface{}{
		"name": "AdminDeletedPayload",
		"fields": []interface{}{
			map[string]interface{}{
				"name": "key",
				"type": "string",
			},
			map[string]interface{}{
				"name":     "admin",
				"optional": true,
				"type":     "message",
				"schema":   new(Admin).Schema(),
			},
		},
		"oneofs": map[string]interface{}{},
	}
}

/*
	Graphify unmarshaler
*/

/* UnmarshalJSON ...*/
func (o *AdminCreatedPayload) UnmarshalJSON(b []byte) error {
	if values, err := utils.MapFromBytes(b); err != nil {
		return err
	} else {
		o.UnmarshalMap(values)
	}
	return nil
}

/* UnmarshalMap populates struct fields from a map, handling decoding for special fields. */
func (o *AdminCreatedPayload) UnmarshalMap(values map[string]interface{}) {
	if val, ok := values["key"].(string); ok {
		o.Key = val
	}
	if val, ok := values["element"].(string); ok {
		o.Element = utils.DecodeBytes(val)
	}
	if val, ok := values["admin"].(map[string]interface{}); ok {
		field := new(Admin)
		field.UnmarshalMap(val)
		o.Admin = field
	}
}

/* UnmarshalJSON ...*/
func (o *AdminUpdatedPayload) UnmarshalJSON(b []byte) error {
	if values, err := utils.MapFromBytes(b); err != nil {
		return err
	} else {
		o.UnmarshalMap(values)
	}
	return nil
}

/* UnmarshalMap populates struct fields from a map, handling decoding for special fields. */
func (o *AdminUpdatedPayload) UnmarshalMap(values map[string]interface{}) {
	if val, ok := values["element"].(string); ok {
		o.Element = utils.DecodeBytes(val)
	}
	if val, ok := values["admin"].(map[string]interface{}); ok {
		field := new(Admin)
		field.UnmarshalMap(val)
		o.Admin = field
	}
}

/* UnmarshalJSON ...*/
func (o *AdminReplacedPayload) UnmarshalJSON(b []byte) error {
	if values, err := utils.MapFromBytes(b); err != nil {
		return err
	} else {
		o.UnmarshalMap(values)
	}
	return nil
}

/* UnmarshalMap populates struct fields from a map, handling decoding for special fields. */
func (o *AdminReplacedPayload) UnmarshalMap(values map[string]interface{}) {
	if val, ok := values["element"].(string); ok {
		o.Element = utils.DecodeBytes(val)
	}
	if val, ok := values["admin"].(map[string]interface{}); ok {
		field := new(Admin)
		field.UnmarshalMap(val)
		o.Admin = field
	}
}

/* UnmarshalJSON ...*/
func (o *AdminDeletedPayload) UnmarshalJSON(b []byte) error {
	if values, err := utils.MapFromBytes(b); err != nil {
		return err
	} else {
		o.UnmarshalMap(values)
	}
	return nil
}

/* UnmarshalMap populates struct fields from a map, handling decoding for special fields. */
func (o *AdminDeletedPayload) UnmarshalMap(values map[string]interface{}) {
	if val, ok := values["key"].(string); ok {
		o.Key = val
	}
	if val, ok := values["admin"].(map[string]interface{}); ok {
		field := new(Admin)
		field.UnmarshalMap(val)
		o.Admin = field
	}
}
