package graphify

// ApplicationConfig ...
type ApplicationConfig struct {
	// Name ...
	Name string `json:"name"`
	// Domain ...
	Domain string `json:"domain"`
	// Logo ...
	Logo string `json:"logo"`
}

// DatabaseConfig ...
type DatabaseConfig struct {
	// DBName ...
	DBName string
	// UserName ...
	UserName string
	// Password ...
	Password string
}
