package graphify

import adminv1 "github.com/amaury95/graphify/models/domain/admin/v1"

// ApplicationConfig ...
type ApplicationConfig struct {
	// Name ...
	Name string `json:"name"`
	// Domain ...
	Domain string `json:"domain"`
	// Logo ...
	Logo string `json:"logo"`
}

// ApplicationConfigInit ...
type ApplicationConfigInit struct {
	// Config ...
	Config ApplicationConfig `json:"config"`
	// Admin ...
	Admin adminv1.Admin `json:"admin"`
	// Password ...
	Password string `json:"password"`
}

// DatabaseConfig ...
type DatabaseConfig struct {
	// Name ...
	Name string
}
