// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: account/v1/event.proto

package accountv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminCreatedPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Element *anypb.Any `protobuf:"bytes,2,opt,name=element,proto3" json:"element,omitempty"`
	Admin   *Admin     `protobuf:"bytes,3,opt,name=admin,proto3" json:"admin,omitempty"`
}

func (x *AdminCreatedPayload) Reset() {
	*x = AdminCreatedPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_v1_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminCreatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminCreatedPayload) ProtoMessage() {}

func (x *AdminCreatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminCreatedPayload.ProtoReflect.Descriptor instead.
func (*AdminCreatedPayload) Descriptor() ([]byte, []int) {
	return file_account_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *AdminCreatedPayload) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AdminCreatedPayload) GetElement() *anypb.Any {
	if x != nil {
		return x.Element
	}
	return nil
}

func (x *AdminCreatedPayload) GetAdmin() *Admin {
	if x != nil {
		return x.Admin
	}
	return nil
}

type AdminUpdatedPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Element *anypb.Any `protobuf:"bytes,1,opt,name=element,proto3" json:"element,omitempty"`
	Admin   *Admin     `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
}

func (x *AdminUpdatedPayload) Reset() {
	*x = AdminUpdatedPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_v1_event_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminUpdatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdatedPayload) ProtoMessage() {}

func (x *AdminUpdatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_event_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdatedPayload.ProtoReflect.Descriptor instead.
func (*AdminUpdatedPayload) Descriptor() ([]byte, []int) {
	return file_account_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *AdminUpdatedPayload) GetElement() *anypb.Any {
	if x != nil {
		return x.Element
	}
	return nil
}

func (x *AdminUpdatedPayload) GetAdmin() *Admin {
	if x != nil {
		return x.Admin
	}
	return nil
}

type AdminReplacedPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Element *anypb.Any `protobuf:"bytes,1,opt,name=element,proto3" json:"element,omitempty"`
	Admin   *Admin     `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
}

func (x *AdminReplacedPayload) Reset() {
	*x = AdminReplacedPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_v1_event_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminReplacedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminReplacedPayload) ProtoMessage() {}

func (x *AdminReplacedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_event_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminReplacedPayload.ProtoReflect.Descriptor instead.
func (*AdminReplacedPayload) Descriptor() ([]byte, []int) {
	return file_account_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *AdminReplacedPayload) GetElement() *anypb.Any {
	if x != nil {
		return x.Element
	}
	return nil
}

func (x *AdminReplacedPayload) GetAdmin() *Admin {
	if x != nil {
		return x.Admin
	}
	return nil
}

type AdminDeletedPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Admin *Admin `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
}

func (x *AdminDeletedPayload) Reset() {
	*x = AdminDeletedPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_v1_event_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminDeletedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeletedPayload) ProtoMessage() {}

func (x *AdminDeletedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_event_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeletedPayload.ProtoReflect.Descriptor instead.
func (*AdminDeletedPayload) Descriptor() ([]byte, []int) {
	return file_account_v1_event_proto_rawDescGZIP(), []int{3}
}

func (x *AdminDeletedPayload) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AdminDeletedPayload) GetAdmin() *Admin {
	if x != nil {
		return x.Admin
	}
	return nil
}

var File_account_v1_event_proto protoreflect.FileDescriptor

var file_account_v1_event_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x2e, 0x76, 0x31, 0x1a, 0x18, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x76, 0x31,
	0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x80, 0x01, 0x0a, 0x13, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x2e, 0x0a, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x65, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x22, 0x6e, 0x0a, 0x13,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x2e, 0x0a, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x65, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x22, 0x6f, 0x0a, 0x14,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x64, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2e, 0x0a, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x65, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x22, 0x50, 0x0a,
	0x13, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x27, 0x0a, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x42,
	0xad, 0x01, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e,
	0x76, 0x31, 0x42, 0x0a, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6d, 0x61,
	0x75, 0x72, 0x79, 0x39, 0x35, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x69, 0x66, 0x79, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2f, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x41, 0x58, 0x58, 0xaa, 0x02,
	0x0a, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0a, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x16, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0xea, 0x02, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x3a, 0x3a, 0x56, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_account_v1_event_proto_rawDescOnce sync.Once
	file_account_v1_event_proto_rawDescData = file_account_v1_event_proto_rawDesc
)

func file_account_v1_event_proto_rawDescGZIP() []byte {
	file_account_v1_event_proto_rawDescOnce.Do(func() {
		file_account_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_account_v1_event_proto_rawDescData)
	})
	return file_account_v1_event_proto_rawDescData
}

var file_account_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_account_v1_event_proto_goTypes = []interface{}{
	(*AdminCreatedPayload)(nil),  // 0: account.v1.AdminCreatedPayload
	(*AdminUpdatedPayload)(nil),  // 1: account.v1.AdminUpdatedPayload
	(*AdminReplacedPayload)(nil), // 2: account.v1.AdminReplacedPayload
	(*AdminDeletedPayload)(nil),  // 3: account.v1.AdminDeletedPayload
	(*anypb.Any)(nil),            // 4: google.protobuf.Any
	(*Admin)(nil),                // 5: account.v1.Admin
}
var file_account_v1_event_proto_depIdxs = []int32{
	4, // 0: account.v1.AdminCreatedPayload.element:type_name -> google.protobuf.Any
	5, // 1: account.v1.AdminCreatedPayload.admin:type_name -> account.v1.Admin
	4, // 2: account.v1.AdminUpdatedPayload.element:type_name -> google.protobuf.Any
	5, // 3: account.v1.AdminUpdatedPayload.admin:type_name -> account.v1.Admin
	4, // 4: account.v1.AdminReplacedPayload.element:type_name -> google.protobuf.Any
	5, // 5: account.v1.AdminReplacedPayload.admin:type_name -> account.v1.Admin
	5, // 6: account.v1.AdminDeletedPayload.admin:type_name -> account.v1.Admin
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_account_v1_event_proto_init() }
func file_account_v1_event_proto_init() {
	if File_account_v1_event_proto != nil {
		return
	}
	file_account_v1_account_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_account_v1_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminCreatedPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_v1_event_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminUpdatedPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_v1_event_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminReplacedPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_v1_event_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminDeletedPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_account_v1_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_v1_event_proto_goTypes,
		DependencyIndexes: file_account_v1_event_proto_depIdxs,
		MessageInfos:      file_account_v1_event_proto_msgTypes,
	}.Build()
	File_account_v1_event_proto = out.File
	file_account_v1_event_proto_rawDesc = nil
	file_account_v1_event_proto_goTypes = nil
	file_account_v1_event_proto_depIdxs = nil
}

/*
	Graphify unmarshaler
*/
