// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: observer/v1/events.proto

package observerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatedPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Element *anypb.Any `protobuf:"bytes,2,opt,name=element,proto3" json:"element,omitempty"`
}

func (x *CreatedPayload) Reset() {
	*x = CreatedPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_observer_v1_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatedPayload) ProtoMessage() {}

func (x *CreatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_observer_v1_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatedPayload.ProtoReflect.Descriptor instead.
func (*CreatedPayload) Descriptor() ([]byte, []int) {
	return file_observer_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *CreatedPayload) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreatedPayload) GetElement() *anypb.Any {
	if x != nil {
		return x.Element
	}
	return nil
}

type UpdatedPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Element *anypb.Any `protobuf:"bytes,1,opt,name=element,proto3" json:"element,omitempty"`
}

func (x *UpdatedPayload) Reset() {
	*x = UpdatedPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_observer_v1_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatedPayload) ProtoMessage() {}

func (x *UpdatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_observer_v1_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatedPayload.ProtoReflect.Descriptor instead.
func (*UpdatedPayload) Descriptor() ([]byte, []int) {
	return file_observer_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatedPayload) GetElement() *anypb.Any {
	if x != nil {
		return x.Element
	}
	return nil
}

type ReplacedPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Element *anypb.Any `protobuf:"bytes,1,opt,name=element,proto3" json:"element,omitempty"`
}

func (x *ReplacedPayload) Reset() {
	*x = ReplacedPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_observer_v1_events_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplacedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplacedPayload) ProtoMessage() {}

func (x *ReplacedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_observer_v1_events_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplacedPayload.ProtoReflect.Descriptor instead.
func (*ReplacedPayload) Descriptor() ([]byte, []int) {
	return file_observer_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *ReplacedPayload) GetElement() *anypb.Any {
	if x != nil {
		return x.Element
	}
	return nil
}

type DeletedPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *DeletedPayload) Reset() {
	*x = DeletedPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_observer_v1_events_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletedPayload) ProtoMessage() {}

func (x *DeletedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_observer_v1_events_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletedPayload.ProtoReflect.Descriptor instead.
func (*DeletedPayload) Descriptor() ([]byte, []int) {
	return file_observer_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *DeletedPayload) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_observer_v1_events_proto protoreflect.FileDescriptor

var file_observer_v1_events_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6f, 0x62, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x52, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2e, 0x0a, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x65,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x40, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2e, 0x0a, 0x07, 0x65, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52,
	0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x41, 0x0a, 0x0f, 0x52, 0x65, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2e, 0x0a, 0x07, 0x65,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41,
	0x6e, 0x79, 0x52, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x22, 0x0a, 0x0e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x42,
	0xb2, 0x01, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x42, 0x0b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x45, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x6d, 0x61, 0x75, 0x72, 0x79, 0x39, 0x35, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x69, 0x66, 0x79,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x2f, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x6f,
	0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4f, 0x58, 0x58, 0xaa,
	0x02, 0x0b, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0b,
	0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x17, 0x4f, 0x62,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0c, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_observer_v1_events_proto_rawDescOnce sync.Once
	file_observer_v1_events_proto_rawDescData = file_observer_v1_events_proto_rawDesc
)

func file_observer_v1_events_proto_rawDescGZIP() []byte {
	file_observer_v1_events_proto_rawDescOnce.Do(func() {
		file_observer_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_observer_v1_events_proto_rawDescData)
	})
	return file_observer_v1_events_proto_rawDescData
}

var file_observer_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_observer_v1_events_proto_goTypes = []interface{}{
	(*CreatedPayload)(nil),  // 0: observer.v1.CreatedPayload
	(*UpdatedPayload)(nil),  // 1: observer.v1.UpdatedPayload
	(*ReplacedPayload)(nil), // 2: observer.v1.ReplacedPayload
	(*DeletedPayload)(nil),  // 3: observer.v1.DeletedPayload
	(*anypb.Any)(nil),       // 4: google.protobuf.Any
}
var file_observer_v1_events_proto_depIdxs = []int32{
	4, // 0: observer.v1.CreatedPayload.element:type_name -> google.protobuf.Any
	4, // 1: observer.v1.UpdatedPayload.element:type_name -> google.protobuf.Any
	4, // 2: observer.v1.ReplacedPayload.element:type_name -> google.protobuf.Any
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_observer_v1_events_proto_init() }
func file_observer_v1_events_proto_init() {
	if File_observer_v1_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_observer_v1_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatedPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_observer_v1_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatedPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_observer_v1_events_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplacedPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_observer_v1_events_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletedPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_observer_v1_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_observer_v1_events_proto_goTypes,
		DependencyIndexes: file_observer_v1_events_proto_depIdxs,
		MessageInfos:      file_observer_v1_events_proto_msgTypes,
	}.Build()
	File_observer_v1_events_proto = out.File
	file_observer_v1_events_proto_rawDesc = nil
	file_observer_v1_events_proto_goTypes = nil
	file_observer_v1_events_proto_depIdxs = nil
}

/*
	Graphql object
*/

/*
	Graphify schema module
*/

/*
	Graphify unmarshaler
*/
