// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: utils/v1/geo.proto

package utilsv1

import (
	utils "github.com/amaury95/protoc-gen-graphify/utils"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	graphql "github.com/graphql-go/graphql"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  float32 `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float32 `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_utils_v1_geo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_utils_v1_geo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_utils_v1_geo_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

var File_utils_v1_geo_proto protoreflect.FileDescriptor

var file_utils_v1_geo_proto_rawDesc = []byte{
	0x0a, 0x12, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x65, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x17,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x66, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x42, 0x0f, 0xfa, 0x42, 0x0c, 0x0a, 0x0a, 0x1d, 0x00, 0x00, 0xb4,
	0x42, 0x2d, 0x00, 0x00, 0xb4, 0xc2, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x12, 0x2d, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x42, 0x0f, 0xfa, 0x42, 0x0c, 0x0a, 0x0a, 0x1d, 0x00, 0x00, 0x34, 0x43, 0x2d,
	0x00, 0x00, 0x34, 0xc3, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x42,
	0x9a, 0x01, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x76, 0x31,
	0x42, 0x08, 0x47, 0x65, 0x6f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3f, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6d, 0x61, 0x75, 0x72, 0x79, 0x39,
	0x35, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x69, 0x66, 0x79, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x75, 0x74, 0x69,
	0x6c, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x76, 0x31, 0xa2, 0x02, 0x03,
	0x55, 0x58, 0x58, 0xaa, 0x02, 0x08, 0x55, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x56, 0x31, 0xca, 0x02,
	0x08, 0x55, 0x74, 0x69, 0x6c, 0x73, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x14, 0x55, 0x74, 0x69, 0x6c,
	0x73, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0xea, 0x02, 0x09, 0x55, 0x74, 0x69, 0x6c, 0x73, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_utils_v1_geo_proto_rawDescOnce sync.Once
	file_utils_v1_geo_proto_rawDescData = file_utils_v1_geo_proto_rawDesc
)

func file_utils_v1_geo_proto_rawDescGZIP() []byte {
	file_utils_v1_geo_proto_rawDescOnce.Do(func() {
		file_utils_v1_geo_proto_rawDescData = protoimpl.X.CompressGZIP(file_utils_v1_geo_proto_rawDescData)
	})
	return file_utils_v1_geo_proto_rawDescData
}

var file_utils_v1_geo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_utils_v1_geo_proto_goTypes = []interface{}{
	(*Location)(nil), // 0: utils.v1.Location
}
var file_utils_v1_geo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_utils_v1_geo_proto_init() }
func file_utils_v1_geo_proto_init() {
	if File_utils_v1_geo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_utils_v1_geo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_utils_v1_geo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_utils_v1_geo_proto_goTypes,
		DependencyIndexes: file_utils_v1_geo_proto_depIdxs,
		MessageInfos:      file_utils_v1_geo_proto_msgTypes,
	}.Build()
	File_utils_v1_geo_proto = out.File
	file_utils_v1_geo_proto_rawDesc = nil
	file_utils_v1_geo_proto_goTypes = nil
	file_utils_v1_geo_proto_depIdxs = nil
}

/*
	Graphql object
*/

/* Argument ... */
func (*Location) Argument() graphql.FieldConfigArgument {
	return graphql.FieldConfigArgument{
		"latitude": &graphql.ArgumentConfig{
			Type: graphql.Float,
		},
		"longitude": &graphql.ArgumentConfig{
			Type: graphql.Float,
		},
	}
}

/* Output ... */
func (*Location) Output() graphql.Output {
	return Location_Object
}

/* Object ... */
func (*Location) Object() *graphql.Object {
	return Location_Object
}

var Location_Object = graphql.NewObject(graphql.ObjectConfig{
	Name: "Location",
	Fields: graphql.Fields{
		"latitude": &graphql.Field{
			Type: graphql.Float,
		},
		"longitude": &graphql.Field{
			Type: graphql.Float,
		},
	},
	Description: "",
})

var Location_Input = graphql.NewInputObject(graphql.InputObjectConfig{
	Name: "Location_Input",
	Fields: graphql.InputObjectConfigFieldMap{
		"latitude": &graphql.InputObjectFieldConfig{
			Type: graphql.Float,
		},
		"longitude": &graphql.InputObjectFieldConfig{
			Type: graphql.Float,
		},
	},
})

/*
	Graphify schema module
*/

/* Schema ... */
func (*Location) Schema() map[string]interface{} {
	return map[string]interface{}{
		"name":  "Location",
		"@type": "type.googleapis.com/utils.v1.Location",
		"fields": []interface{}{
			map[string]interface{}{
				"name": "latitude",
				"type": "float",
			},
			map[string]interface{}{
				"name": "longitude",
				"type": "float",
			},
		},
		"oneofs": map[string]interface{}{},
	}
}

/*
	Graphify unmarshaler
*/

/* UnmarshalJSON ...*/
func (o *Location) UnmarshalJSON(b []byte) error {
	if values, err := utils.MapFromBytes(b); err != nil {
		return err
	} else {
		o.UnmarshalMap(values)
	}
	return nil
}

/* UnmarshalMap populates struct fields from a map, handling decoding for special fields. */
func (o *Location) UnmarshalMap(values map[string]interface{}) {
	if val, ok := values["latitude"].(float64); ok {
		o.Latitude = float32(val)
	}
	if val, ok := values["longitude"].(float64); ok {
		o.Longitude = float32(val)
	}
}
